### ISSUE TITLE
wiki.musicontology.com is broken

### ISSUE THREAD

**Issue by ju1ius** [motools/musicontology.com#2]
Every page (like `http://wiki.musicontology.com/index.php/Examples`) throws a database error:

```
A database query syntax error has occurred. This may indicate a bug in the software. The last attempted database query was:

    (SQL query hidden)

from within function "SqlBagOStuff::set". Database returned error "1114: The table 'mo_objectcache' is full (localhost)".
```

**Comment by moustaki** [comment]
We're desperately trying to move the wiki over to github as we keep getting spammed. The database server has run out of disk again. I'll try to restore some space on it, but would really like to switch that server off once and for all.

**Comment by moustaki** [comment]
I disabled all editing on the wiki for the time being and cleaned up the db to gain some space - it should now be available

**Comment by moustaki** [comment]
Arg - something went wrong when running a script trying to remove some spam - and this aggregation page seems to have been accidentally deleted. I hope there's a copy lurking somewhere (most of the examples are in the musicontology repo on github).
