### ISSUE TITLE
Following internal links does not update navigator location

### ISSUE THREAD

**Issue by ironchicken** [motools/musicontology.com#3]
When I follow one of the links in the table of contents to view information about a class or property, there's a JavaScript effect that scrolls the document to the `<section>`. However, this doesn't actually change the current `window.location`. Consequently, if I want to navigate back to the table of contents I can't use my browser's back function. And this is true of _all_ the internal links, not just the table of contents links. So if I've followed a link to a property from a class, I can't use the back function to go back to the class. I wonder if the JavaScript scrolling thing can be modified to result in a new history point (i.e. a URL visit)? I notice that the `<a>` links do point to the `<section>`'s by `id`, so I think it might just be a case of altering the `onClick` handler defined from lines 144-157 of `mo.js` to modify the `window.location` property.

**Comment by moustaki** [comment]
Fixed now - thank you!
