### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by echo66** [motools/musicontology.com#5]
Did someone forget to pay the yearly fee? :P

**Comment by fgiasson** [comment]
@moustaki looks like it got hacked or something. Who has access to that server?

**Comment by moustaki** [comment]
@fgiasson it looks like the DNS was indeed taken over:
http://www.domainiq.com/domain?musicontology.comhttp
http://www.domainiq.com/domain?musicontology.com://
http://www.domainiq.com/domain?musicontology.comwww.domainiq.com
http://www.domainiq.com/domain?musicontology.com/domain?
http://www.domainiq.com/domain?musicontology.commusicontology.com
http://www.domainiq.com/domain?musicontology.com , just 9 hours ago :(
The server itself is fine. Do you know how we can get it back?

@moustaki https://github.com/moustaki looks like it got hacked or
something. Who has access to that server?

**Comment by fgiasson** [comment]
@moustaki are you saying that someone forgot to renew the domain and this is what is happening atm? I did transfer it to you years ago I think, are you still the one that had it or your transfered it back to someone else?

**Comment by fgiasson** [comment]
Fixed. This domain is owned by OpenLinks and was not on autorenew anymore.

They paid for its renewal and the auto-renew has been re-actived.

Please try to access the page, it should now be working. If it doesn't [yet] it may means that it didn't propagate to you (yet).

**Comment by boferri** [comment]
it's working (again). thx a lot @fgiasson for fixing the issue.
